/**
 * Extends HashMap - contains a String specifying the value for each grid cell
 * The key String is a concatenation of the ROWS.name() and COLUMNS.name() values 
 * 
 * @author Thomas Wiegand (wieg0002)
 * @version 1.0 
 * 
 */

package domain;

import java.util.HashMap;

public class MySchedule extends HashMap<String, String> {
	
	/**
	 * Needed for serializing this class. Generated by eclipse
	 */
	private static final long serialVersionUID = 1929894473386042175L;

	public void atPut(String row, String column, String scheduledClass ) {
		put( row + column, scheduledClass );
	}

	public String atGet(String row, String column ) {
		return get( row + column );
	}

}
